name: Deploy Workflow

on:
  - push
  - pull_request

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout deploy_source repository
      uses: actions/checkout@v4
      with:
        repository: SAST-Mathematic-SIG/blog_deploy_source
        path: deploy_source
    
    - name: Checkout blog repository
      uses: actions/checkout@v4
      with:
        path: deploy_source/content

    - name: Print current file tree
      run: ls -R deploy_source

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3

    - name: Build
      run: hugo --minify

    # - name: Deploy
    #   uses: peaceiris/actions-gh-pages@v3
    #   if: github.ref == 'refs/heads/main'
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./public